# intended for testing

services:
  munin-server:
    build: ./
    #container_name: es
    #environment:
    #  discovery.type: single-node
    #  ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "8080:8080"
    #healthcheck:
    #  test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
    #  interval: 10s
    #  timeout: 10s
    #  retries: 3
    #networks:
    #  - elastic
  samplenode:
    image: dennistt/munin-node:latest
    stop_signal: SIGKILL
    environment:
      PLUGINS: cpu load

