version: '3.4'

# intended for testing

services:
  munin-server:
    build: ../
    ports:
      - "8080:8080"
    volumes:
      - "./muninconf.d/:/etc/munin/munin-conf.d:ro"
  samplenode:
    image: dennistt/munin-node:latest
    stop_signal: SIGKILL
    environment:
      PLUGINS: cpu load

