version: '3.4'

# intended for testing

services:
  munin-server:
    build: ../
    environment:
      TZ: Europe/Zurich
    ports:
      - "8080:8080"
    volumes:
      - "./muninconf.d/:/etc/munin/munin-conf.d:ro"
      - "./data/var-lib-munin/:/var/lib/munin/"
  samplenode:
    image: dennistt/munin-node:latest
    stop_signal: SIGKILL
    environment:
      PLUGINS: cpu load

